import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import sharp, { type Exif } from 'sharp';
import {
  DEMO_DEFAULT_START,
  photoCoords,
  photoTakenAt,
  type DemoPhotoSpec,
} from '@pinlog/schema/fixtures';

/** Committed demo JPEGs: packages/schema/fixtures/photos/<media_id>.jpg (generated by this file, EXIF stamped). */
export const FIXTURE_PHOTOS_DIR = resolve(import.meta.dirname, '../../../schema/fixtures/photos');
const REPO_ROOT = resolve(import.meta.dirname, '../../../../');

const esc = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/** Decimal degrees → EXIF rational triple string (deg/1 min/1 sec*100/100), as libvips expects. */
function dms(value: number): string {
  const abs = Math.abs(value);
  const deg = Math.floor(abs);
  const minFloat = (abs - deg) * 60;
  const min = Math.floor(minFloat);
  const sec = Math.round((minFloat - min) * 60 * 10000);
  return `${deg}/1 ${min}/1 ${sec}/10000`;
}

function exifFor(spec: DemoPhotoSpec, start_date: string): Exif {
  const coords = photoCoords(spec);
  const taken = photoTakenAt(spec, start_date);
  const exif: Exif = {
    IFD0: { Make: 'Pinlog', Model: 'Seed Camera', Orientation: '1', Software: 'pinlog seed' },
    IFD2: {},
    IFD3: {},
  };
  if (taken) {
    exif.IFD2!.DateTimeOriginal = `${taken.slice(0, 10).replace(/-/g, ':')} ${taken.slice(11, 19)}`;
    exif.IFD2!.OffsetTimeOriginal = '-04:00';
  }
  if (coords) {
    exif.IFD3!.GPSLatitudeRef = coords.lat >= 0 ? 'N' : 'S';
    exif.IFD3!.GPSLatitude = dms(coords.lat);
    exif.IFD3!.GPSLongitudeRef = coords.lng >= 0 ? 'E' : 'W';
    exif.IFD3!.GPSLongitude = dms(coords.lng);
  }
  return exif;
}

/** A gradient card with the label, stamped with GPS + DateTimeOriginal so the ingest path can be exercised end to end. */
export async function generateDemoPhoto(
  spec: DemoPhotoSpec,
  start_date: string = DEMO_DEFAULT_START,
): Promise<Uint8Array> {
  const landscape = spec.orientation === 'landscape';
  const w = landscape ? 1600 : 1200;
  const h = landscape ? 1200 : 1600;
  const [c0, c1] = spec.palette;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${c0}"/><stop offset="1" stop-color="${c1}"/></linearGradient>
    <radialGradient id="s" cx="0.7" cy="0.25" r="0.6"><stop offset="0" stop-color="#ffffff" stop-opacity="0.35"/><stop offset="1" stop-color="#ffffff" stop-opacity="0"/></radialGradient>
  </defs>
  <rect width="100%" height="100%" fill="url(#g)"/>
  <rect width="100%" height="100%" fill="url(#s)"/>
  <circle cx="${w * 0.72}" cy="${h * 0.28}" r="${Math.min(w, h) * 0.12}" fill="#ffffff" fill-opacity="0.25"/>
  <path d="M0 ${h * 0.78} Q ${w * 0.25} ${h * 0.68} ${w * 0.5} ${h * 0.76} T ${w} ${h * 0.7} V ${h} H 0 Z" fill="#000000" fill-opacity="0.18"/>
  <text x="${w * 0.06}" y="${h * 0.88}" fill="#ffffff" font-size="${Math.round(w * 0.045)}" font-family="Helvetica, Arial, sans-serif" font-weight="700">${esc(spec.label)}</text>
  <text x="${w * 0.06}" y="${h * 0.93}" fill="#ffffff" fill-opacity="0.8" font-size="${Math.round(w * 0.025)}" font-family="Helvetica, Arial, sans-serif">Pinlog demo photo · ${esc(spec.caption)}</text>
</svg>`;
  const buf = await sharp(Buffer.from(svg))
    .jpeg({ quality: 82, mozjpeg: true })
    .withExif(exifFor(spec, start_date))
    .toBuffer();
  return new Uint8Array(buf);
}

/** Stamp GPS + DateTimeOriginal onto a real team photo so auto-assign still works. */
async function stampSourcePhoto(
  spec: DemoPhotoSpec,
  sourcePath: string,
  start_date: string,
): Promise<Uint8Array> {
  const buf = await sharp(sourcePath)
    .rotate()
    .jpeg({ quality: 88, mozjpeg: true })
    .withExif(exifFor(spec, start_date))
    .toBuffer();
  return new Uint8Array(buf);
}

export const fixturePhotoPath = (media_id: string, dir = FIXTURE_PHOTOS_DIR) =>
  join(dir, `${media_id}.jpg`);

/** Read the committed JPEG; generate (and write) it when missing or when `regenerate` is set. */
export async function loadOrGenerateDemoPhoto(
  spec: DemoPhotoSpec,
  opts: { dir?: string; regenerate?: boolean; start_date?: string } = {},
): Promise<{ bytes: Uint8Array; generated: boolean }> {
  const dir = opts.dir ?? FIXTURE_PHOTOS_DIR;
  const path = fixturePhotoPath(spec.id, dir);
  const start_date = opts.start_date ?? DEMO_DEFAULT_START;
  if (!opts.regenerate) {
    try {
      return { bytes: new Uint8Array(await readFile(path)), generated: false };
    } catch {
      /* fall through */
    }
  }
  if (spec.source) {
    try {
      const bytes = await stampSourcePhoto(spec, resolve(REPO_ROOT, spec.source), start_date);
      await mkdir(dir, { recursive: true });
      await writeFile(path, bytes);
      return { bytes, generated: true };
    } catch {
      /* source missing — fall through to the labelled card */
    }
  }
  const bytes = await generateDemoPhoto(spec, start_date);
  await mkdir(dir, { recursive: true });
  await writeFile(path, bytes);
  return { bytes, generated: true };
}
